"'Profile - Settings' As screen":

    "'Background Color_3' As rectangle":
        BorderStyle: =BorderStyle.None
        Height: =111
        Width: =App.Width
        ZIndex: =1

    "'Back Button_4' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ArrowLeft
        OnSelect: =Navigate(Profile, ScreenTransition.Cover)
        Width: =48
        X: =30
        Y: =30
        ZIndex: =2

    Label2_2 As label:
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        Height: =70
        Size: =26
        Text: |-
            ="Settings
            "
        Width: =149
        X: =89
        Y: =20
        ZIndex: =3

    Label16 As label:
        Font: =Font.Lato
        Height: =70
        Size: =21
        Text: ="Notifications"
        Width: =233
        X: =30
        Y: =146
        ZIndex: =4

    Toggle1 As toggleSwitch:
        Height: =27
        Size: =21
        Width: =114
        X: =Parent.Width - 125
        Y: =167
        ZIndex: =5

    Label17 As label:
        Color: =RGBA(221, 79, 14, 1)
        Font: =Font.Lato
        Height: =70
        Size: =21
        Text: ="Logout"
        Width: =120
        X: =30
        Y: =216
        ZIndex: =6

