TrainingTrackerHome As screen:

    Rectangle4_5 As rectangle:
        Fill: =RGBA(25, 53, 110, 1)
        Width: =640
        ZIndex: =1

    HomeTitle As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.Lato
        Height: =74
        Size: =25
        Text: ="Training Tracker"
        Width: =474
        X: =81
        Y: =15
        ZIndex: =2

