"'Training Tracker - View Training Details' As screen":

    Container1_3 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        Container3_3 As groupContainer.horizontalAutoLayoutContainer:
            Fill: =RGBA(0, 16, 96, 1)
            Height: =225
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =1

            HomeTitle_3 As label:
                Align: =Align.Center
                AlignInContainer: =AlignInContainer.Center
                Color: =RGBA(255, 255, 255, 1)
                Font: =Font.Lato
                Height: =74
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =26
                Text: =_currentSelectedTraining.Training
                Width: =Parent.Width
                X: =83
                Y: =127
                ZIndex: =1

        Container4_2 As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =7
            Height: =225
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =2

            Container9 As groupContainer.manualLayoutContainer:
                Height: =Parent.Height
                LayoutMinHeight: =112
                LayoutMinWidth: =250
                Width: =Parent.Width
                ZIndex: =1

                Label10 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Presenter: "
                    Width: =175
                    X: =40
                    Y: =40
                    ZIndex: =1

                Label10_1 As label:
                    Height: =70
                    Size: =21
                    Text: =_currentSelectedTraining.'Presenter/Host'.DisplayName
                    Width: =425
                    X: =215
                    Y: =40
                    ZIndex: =2

                Label10_2 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Date: "
                    Width: =175
                    X: =40
                    Y: =110
                    ZIndex: =3

                Label10_3 As label:
                    Height: =70
                    Size: =21
                    Text: ="📆 " & _currentSelectedTraining.TrainingStartDate
                    Width: =425
                    X: =215
                    Y: =110
                    ZIndex: =4

                Label10_4 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Type(s): "
                    Width: =175
                    X: =40
                    Y: =320
                    ZIndex: =5

                Label10_5 As label:
                    Height: =70
                    Size: =21
                    Text: =Concat(_currentSelectedTraining.MCLE_Category, Value, ", ")
                    Width: =425
                    X: =215
                    Y: =320
                    ZIndex: =6

                Label10_6 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Format: "
                    Width: =175
                    X: =40
                    Y: =180
                    ZIndex: =7

                Label10_7 As label:
                    Height: =70
                    Size: =21
                    Text: =_currentSelectedTraining.TrainingFormat.Value
                    Width: =425
                    X: =215
                    Y: =180
                    ZIndex: =8

                Label10_8 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Location: "
                    Width: =175
                    X: =40
                    Y: =458
                    ZIndex: =9

                Label10_9 As label:
                    Height: =70
                    Size: =21
                    Text: =If(IsBlank(_currentSelectedTraining.Location), "N/A", _currentSelectedTraining.Location)
                    Width: =425
                    X: =215
                    Y: =458
                    ZIndex: =10

                Label10_10 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Address: "
                    Width: =175
                    X: =40
                    Y: =528
                    ZIndex: =11

                Label10_11 As label:
                    Height: =122
                    Size: =21
                    Text: =If(IsBlank(_currentSelectedTraining.Address), "N/A", _currentSelectedTraining.Address)
                    VerticalAlign: =VerticalAlign.Top
                    Width: =398
                    X: =215
                    Y: =541
                    ZIndex: =12

                Label10_12 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Status: "
                    Width: =175
                    X: =40
                    Y: =663
                    ZIndex: =13

                Label10_13 As label:
                    Height: =70
                    Size: =21
                    Text: =_currentSelectedTrainingStatus
                    Width: =425
                    X: =215
                    Y: =663
                    ZIndex: =14

                Label10_14 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="Hours: "
                    Width: =175
                    X: =40
                    Y: =250
                    ZIndex: =15

                Label10_15 As label:
                    Height: =70
                    Size: =21
                    Text: =_currentSelectedTraining.Hours
                    Width: =425
                    X: =215
                    Y: =250
                    ZIndex: =16

                Button7 As button:
                    Height: =70
                    OnSelect: =Navigate('Training Tracker - Check In', ScreenTransition.CoverRight);
                    Size: =24
                    Text: ="Check-In"
                    Visible: |-
                        =If(
                            _currentSelectedTrainingStatus = "In-progress" And LookUp(
                                MCLETrainingAttendance,
                                TrainingID = _currentSelectedTraining.ID And Attendee = User().FullName,
                                IsBlank('Checkout Time')
                            ),
                            true,
                            false
                        )
                    Width: =Parent.Width - 120
                    X: |+
                        =60
                        
                    Y: =Parent.Height - 120
                    ZIndex: =17

                Button7_2 As button:
                    DisplayMode: =If(Label10_17.Text = "Yes", DisplayMode.Disabled, DisplayMode.Edit)
                    Height: =70
                    OnSelect: |
                        =If(
                            IsBlank(
                                LookUp(
                                    MCLETrainingAttendance,
                                    Attendee = User().FullName && _currentSelectedTraining.ID = TrainingID
                                )
                            ),
                            Patch(
                                MCLETrainingAttendance,
                                Defaults(MCLETrainingAttendance),
                                {
                                    RSVP: true,
                                    Attendee: User().FullName,
                                    TrainingID: _currentSelectedTraining.ID
                                }
                            );
                            Office365Outlook.V4CalendarPostItem(
                                LookUp(
                                    Office365Outlook.CalendarGetTablesV2().value,
                                    name = "Calendar"
                                ).id,
                                _currentSelectedTraining.Training,
                                _currentSelectedTraining.TrainingStartDate,
                                _currentSelectedTraining.TrainingEndDay,
                                "Pacific Standard Time",
                                {location: _currentSelectedTraining.Location & " " & _currentSelectedTraining.Address,
                                importance: "normal",
                                isReminderOn: true,
                                reminder: 60}
                            );
                            Navigate(
                                'Training Tracker - RSVP Success',
                                ScreenTransition.CoverRight
                            );
                            ,
                            Notify("You're already enrolled in this course.")
                        );
                    Size: =24
                    Text: ="RSVP"
                    Visible: =If(_currentSelectedTrainingStatus = "In-progress" || _currentSelectedTrainingStatus = "Completed", false, true)
                    Width: =Parent.Width - 120
                    X: =60
                    Y: =Parent.Height - 120
                    ZIndex: =18

                Button7_4 As button:
                    Height: =70
                    OnSelect: |
                        =Navigate('Training Tracker - MCLE Certificate', ScreenTransition.CoverRight, {MeetingRecord: _currentSelectedTraining })
                    Size: =24
                    Text: ="Generate Certificate"
                    Visible: |-
                        =If(
                            _currentSelectedTrainingStatus = "Completed" && LookUp(
                                MCLETrainingAttendance,
                                Attendee = User().FullName && TrainingID = _currentSelectedTraining.ID,
                                Attended
                            ) = true,
                            true,
                            false
                        )
                    Width: =Parent.Width - 120
                    X: |
                        =60
                    Y: =Parent.Height - 120
                    ZIndex: =19

                Label10_16 As label:
                    FontWeight: =FontWeight.Bold
                    Height: =70
                    Size: =21
                    Text: |-
                        ="RSVP:"
                    Width: =175
                    X: =40
                    Y: =733
                    ZIndex: =20

                Label10_17 As label:
                    Height: =70
                    Size: =21
                    Text: =If(LookUp(MCLETrainingAttendance, TrainingID = _currentSelectedTraining.ID && Attendee = User().FullName, RSVP), "Yes", "No")
                    Width: =425
                    X: =215
                    Y: =733
                    ZIndex: =21

                Button7_1 As button:
                    Height: =70
                    OnSelect: =Navigate('Training Tracker - Check Out', ScreenTransition.CoverRight);
                    Size: =24
                    Text: ="Check-Out"
                    Visible: |-
                        =If(
                            _currentSelectedTrainingStatus = "In-progress" And LookUp(
                                MCLETrainingAttendance,
                                TrainingID = _currentSelectedTraining.ID And Attendee = User().FullName,
                                !IsBlank('Checkout Time')
                            ),
                            true,
                            false
                        )
                    Width: =Parent.Width - 120
                    X: |
                        =60
                    Y: =Parent.Height - 120
                    ZIndex: =22

    "'Back Button_16' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ArrowLeft
        OnSelect: =Navigate('Training Tracker - View Trainings', ScreenTransition.Cover)
        Width: =40
        X: =30
        Y: =Container3_3.Height / 2 - 21
        ZIndex: =2

