"'Training Tracker - MCLE Certificate' As screen.'printableLayout_A4Landscape_ver1.0'":
    Height: =8.5*92
    OnVisible: |
        =UpdateContext({
            Credits: [
                //{Title: "General MCLE", Hours: 32},
                //{Title: "Legal Ethics", Hours: 32},
                ////{Title: "Recognition & Elimination of Bias", Hours: 32},
                {Title: "Implicit Bias", Hours: 32},
                //{Title: "Prevention & Detection Competence", Hours: 32},
                //{Title: "Wellness Competence", Hours: 32},
                //{Title: "Technology in the Practice of Law", Hours: 32},
                //{Title: "Civility in the Legal Profession", Hours: 32}
            ],
            ProviderName: "Santa Barbara Public Defender",
            ProviderNum: 123456789,
            Activity: {
                Title: "MCLE Activity",
                Location: "Remote",
                Date: Date(2024, 2, 13),
                Time: Time(20, 15, 45)
            },
            Index: 1,
            AttendanceRecord: First(AttendanceRecords)
        });
        
        If(IsBlankOrError(MeetingRecord),
            UpdateContext({
                MeetingRecord: First(MCLETrainings_1)
            })
        );
    Width: =11*92

    MCLE_Certificate_Outer_Border As rectangle:
        BorderThickness: =5
        Fill: =RGBA(0, 0, 0, 0)
        Height: =754
        Width: =Parent.Width - 2*Self.X
        X: =12
        Y: =18
        ZIndex: =3

    MCLE_Certificate_Inner_Border As rectangle:
        BorderThickness: =1
        Fill: =RGBA(0, 0, 0, 0)
        Height: |
            =Parent.Height - 2*Self.Y
        Width: =Parent.Width - 2 * Self.X
        X: =32
        Y: =29
        ZIndex: =4

    MCLE_Certificate_Upper_Text As label:
        Align: =Align.Center
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =49
        Size: =16
        Text: |-
            ="Minimum Continuing Legal Education (MCLE) Credit Hours Awarded for the Above Activity:"
        Width: =860
        X: =(Parent.Width - Self.Width)/2
        Y: =280
        ZIndex: =5

    MCLE_Certificate_Table As htmlViewer:
        AutoHeight: =true
        Font: =Font.Georgia
        Height: =330
        HtmlText: |-
            ="<table style='table-layout: fixed;width: 100%;border-collapse: collapse;' border>"&
            "<thead style='color: #169; font-size: 1.2em'><th style='width: 70%;'>Credit Type</th><th>Credit Hours</th></thead>"&
            "<tbody>"&
            Concat(MeetingRecord.MCLE_Category.Value, "<tr><td style='text-align: right;padding:5px;'>"&Value&"</td><td style='padding:5px;text-align:center;'>"&DateDiff(MeetingRecord.TrainingStartDate, MeetingRecord.TrainingEndDay, TimeUnit.Hours) / CountRows(MeetingRecord.MCLE_Category.Value) &"</td></tr>", "")&
            "</tbody><tfoot>"&
            "<tr><th style='text-align: right;padding:2%;border-left-color: transparent;border-bottom-color: transparent;color: #169; font-size: 1.2em'>Total</th><td style='padding:5px;'>"&DateDiff(MeetingRecord.TrainingStartDate, MeetingRecord.TrainingEndDay, TimeUnit.Hours)&"</td></tr>"&
            "</tfoot></table>"
        Size: =10
        Width: =410
        X: =(Parent.Width-Self.Width)/2
        Y: =339
        ZIndex: =6

    MCLE_Certificate_Title As htmlViewer:
        AutoHeight: =true
        Font: =Font.Georgia
        Height: =294
        HtmlText: |-
            ="<center>California MCLE Certificate of <font color='#169'>Attendance</font></center>"
        Size: =32
        Width: =531
        X: =(Parent.Width-Self.Width)/2
        Y: =40
        ZIndex: =7

    MCLE_Certificate_Lower_Text As label:
        Align: =Align.Center
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =55
        Size: =16
        Text: ="Below section is to be completed by the California Licensee and/or the Provider after participation in the activity"
        Width: =860
        X: =(Parent.Width - Self.Width)/2
        Y: =626
        ZIndex: =8

    MCLE_Certificate_CA_Name As htmlViewer:
        AutoHeight: =true
        Font: =Font.Georgia
        Height: =103
        HtmlText: |-
            ="<p style='margin-bottom: 2px;line-height:0.5;'>"&User().FullName&"</p>"&
            "<p style='border-top: 2px solid;text-align: center;'><b>Name of CA Licensee</b> (<i>print name</i>)</p>"
        Size: |
            =11
        Width: =302
        X: =75
        Y: =691
        ZIndex: =9

    MCLE_Certificate_CA_Bar As htmlViewer:
        AutoHeight: =true
        Font: =Font.Georgia
        Height: =103
        HtmlText: |-
            ="<p style='margin-bottom: 2px;line-height:0.5;'>"&Left(User().EntraObjectId, 10)&"</p>"&
            "<p style='border-top: 2px solid;text-align: center;'><b>CA Bar Number</b></p>"
        Width: =155
        X: =435
        Y: =691
        ZIndex: =10

    MCLE_Certificate_CA_Signature As htmlViewer:
        AutoHeight: =true
        Font: =Font.Georgia
        Height: =103
        HtmlText: |-
            ="<p style='margin-bottom: 2px;line-height:0.5;'>&nbsp;</p>"&
            "<p style='border-top: 2px solid;text-align: center;'><b>Signature of CA Licensee</b></p>"
        Width: =302
        X: =658
        Y: =691
        ZIndex: =11

    MCLE_Certificate_Provider_Name As label:
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =32
        Text: |-
            ="Provider Name: "& ProviderName
        Width: =617
        X: =78
        Y: =154
        ZIndex: =12

    MCLE_Certificate_Activity_Title As label:
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =32
        Text: |-
            ="Title of Activity: "& MeetingRecord.Training
        Width: =860
        X: =78
        Y: =185
        ZIndex: =13

    MCLE_Certificate_Activity_Location As label:
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =31
        Text: |-
            ="Location of the Activity: "& MeetingRecord.Location
        Width: =860
        X: =78
        Y: =213
        ZIndex: =14

    MCLE_Certificate_Activity_Time As label:
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =31
        Text: |-
            ="Date & Time of the Activity: "& Text(MeetingRecord.TrainingStartDate, DateTimeFormat.ShortDateTime)
        Width: =860
        X: =78
        Y: =246
        ZIndex: =15

    MCLE_Certificate_Provider_Number As label:
        AutoHeight: =true
        Font: =Font.Georgia
        FontWeight: =FontWeight.Bold
        Height: =31
        Text: |-
            ="Provider No.: "& ProviderNum
        Width: =279
        X: =643
        Y: =154
        ZIndex: =16

    MCLE_Certificate_Timer As timer:
        AutoPause: =false
        AutoStart: =true
        Duration: =1
        OnTimerEnd: |-
            =Office365Outlook.SendEmailV2(User().Email, "MCLE Certificate", "See your freshly generated MCLE Certificate of Attendance!", {
                Attachments: [{
                    Name: "MCLE_Certificate.pdf",
                    ContentBytes: PDF('Training Tracker - MCLE Certificate', {Orientation: PaperOrientation.Landscape, Size: PaperSize.Letter, Margin: "0"})
                }]
            });
            
            Back();
        Visible: =false
        X: =963
        ZIndex: =17

