"'Training Tracker - Attendee List' As screen":

    Container12_2 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutGap: =20
        LayoutJustifyContent: =LayoutJustifyContent.SpaceBetween
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        Container14_5 As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =RGBA(50, 86, 160, 1)
            FillPortions: =0
            Height: ='Background Color_9'.Height
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            Width: ='Background Color_9'.Width
            X: =
            Y: =
            ZIndex: =1

            Icon11_5 As icon.ArrowLeft:
                Color: =RGBA(255, 255, 255, 1)
                Icon: =Icon.ArrowLeft
                OnSelect: =Back();
                X: =40
                Y: =40
                ZIndex: =1

            Label15_6 As label:
                Align: =Align.Center
                Color: =RGBA(255, 255, 255, 1)
                Font: =Font.Lato
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =25
                Text: ="Generate Certificates"
                Width: =487
                X: =115
                Y: =15
                ZIndex: =2

        Label20_2 As label:
            Height: =70
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            Size: =21
            Text: |-
                ="Attendees:"
            Width: =560
            ZIndex: =4

        "Gallery5 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0'":
            DelayItemLoading: =true
            Items: =Filter(MCLETrainingAttendance, TrainingID = Training.ID)
            Layout: =Layout.Vertical
            LayoutMinHeight: =287
            LayoutMinWidth: =320
            LoadingSpinner: =LoadingSpinner.Data
            TemplatePadding: =0
            TemplateSize: =104
            ZIndex: =5

            Image2 As image:
                Height: =72
                Image: =LookUp(Users, 'Full Name' = ThisItem.Attendee).'Profile Picture'
                OnSelect: =Select(Parent)
                RadiusBottomLeft: =8
                RadiusBottomRight: =8
                RadiusTopLeft: =8
                RadiusTopRight: =8
                Width: =72
                X: =16
                Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                ZIndex: =1

            Title5 As label:
                FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                Height: =Self.Size * 1.8
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =ThisItem.Title
                VerticalAlign: =VerticalAlign.Top
                Width: =Parent.TemplateWidth - 173
                X: =103
                Y: =(Parent.TemplateHeight - (Self.Size * 1.8 + Subtitle4.Size * 1.8)) / 2
                ZIndex: =2

            Subtitle4 As label:
                FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                Height: =Self.Size * 1.8
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =ThisItem.Attendee
                VerticalAlign: =VerticalAlign.Top
                Width: =Title5.Width
                X: =96
                Y: =41
                ZIndex: =3

            Separator1 As rectangle:
                Height: =8
                OnSelect: =Select(Parent)
                Width: =Parent.TemplateWidth
                Y: =Parent.TemplateHeight - Self.Height
                ZIndex: =5

