"'Training Tracker - View Trainings' As screen":

    Container1_1 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        Container3_1 As groupContainer.horizontalAutoLayoutContainer:
            Fill: =RGBA(0, 16, 96, 1)
            Height: =225
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =1

            HomeTitle_2 As label:
                Align: =Align.Center
                AlignInContainer: =AlignInContainer.Center
                Color: =RGBA(255, 255, 255, 1)
                Font: =Font.Lato
                Height: =74
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =26
                Text: ="My Trainings"
                Width: =Parent.Width
                X: =83
                Y: =127
                ZIndex: =1

        Container4_1 As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =7
            Height: =225
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =2

            "Gallery6 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0'":
                DelayItemLoading: =true
                Items: =Courses
                Layout: =Layout.Vertical
                LayoutMinHeight: =287
                LayoutMinWidth: =320
                LoadingSpinner: =LoadingSpinner.Data
                TemplatePadding: =20
                TemplateSize: =200
                Visible: =trainingsListView
                ZIndex: =1

                Rectangle6 As rectangle:
                    Fill: =RGBA(241, 244, 249, 1)
                    Height: =199
                    OnSelect: =Select(Parent)
                    Width: =Parent.TemplateWidth
                    Y: =1
                    ZIndex: =1

                Subtitle1 As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =48
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0
                    PaddingLeft: =0
                    PaddingRight: =0
                    PaddingTop: =0
                    Size: =24
                    Text: =ThisItem.CourseTitle
                    VerticalAlign: =VerticalAlign.Top
                    Width: =467
                    X: =39
                    Y: =20
                    ZIndex: =2

                NextArrow1 As icon.ChevronRight:
                    AccessibleLabel: =Self.Tooltip
                    Color: =RGBA(166, 166, 166, 1)
                    Height: =50
                    Icon: =Icon.ChevronRight
                    OnSelect: =Select(Parent)
                    PaddingBottom: =16
                    PaddingLeft: =16
                    PaddingRight: =16
                    PaddingTop: =16
                    Tooltip: ="View item details"
                    Width: =50
                    X: =Parent.TemplateWidth - Self.Width - 12
                    Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                    ZIndex: =3

                CourseDate As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =37
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0.00
                    PaddingTop: =0.00
                    Size: =18
                    Text: ="📆 " & ThisItem.CourseDate
                    VerticalAlign: =VerticalAlign.Top
                    Width: =499
                    X: =39
                    Y: =75
                    ZIndex: =4

                CourseFormat As button:
                    Fill: =Switch(ThisItem.CourseFormat.Value, "Online", Color.LightGreen, "In-person", Color.LightBlue, "Hybrid", Color.DarkSalmon)
                    Height: =26.65
                    OnSelect: =Select(Parent)
                    PaddingBottom: =3.51
                    PaddingLeft: =3.51
                    PaddingRight: =3.50
                    PaddingTop: =3.50
                    Size: =12
                    Text: =ThisItem.CourseFormat.Value
                    Width: =127.31
                    X: =39
                    Y: =112
                    ZIndex: =5

                CourseStatus As label:
                    Color: =Switch(ThisItem.CourseStatus.Value, "Available", Color.Blue, "Completed", Color.Green, "In-progress", Color.Orange)
                    Height: =23.14
                    OnSelect: =Select(Parent)
                    PaddingBottom: =3.51
                    PaddingLeft: =3.51
                    PaddingRight: =3.50
                    PaddingTop: =3.50
                    Size: =12
                    Text: =ThisItem.CourseStatus.Value
                    Width: =137.10
                    X: =181
                    Y: =114
                    ZIndex: =6

                CoursePresenter As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =25
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0.00
                    PaddingTop: =0.00
                    Size: =14
                    Text: |-
                        ="Presenter:    " & ThisItem.'Presenter/Panelist'.DisplayName
                    VerticalAlign: =VerticalAlign.Top
                    Width: =279
                    X: =39
                    Y: =157
                    ZIndex: =7

                CourseID As label:
                    FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                    Height: =25
                    OnSelect: =Select(Parent)
                    PaddingBottom: =0.00
                    PaddingLeft: =0.00
                    PaddingRight: =0.00
                    PaddingTop: =0.00
                    Size: =14
                    Text: |-
                        ="ID:    " & ThisItem.CourseID
                    VerticalAlign: =VerticalAlign.Top
                    Width: =159
                    X: =379
                    Y: =157
                    ZIndex: =8

    "'Back Button_12' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ArrowLeft
        OnSelect: =Navigate('Training Tracker - Home', ScreenTransition.Cover)
        Width: =40
        X: =30
        Y: =Container3_1.Height / 2 - 21
        ZIndex: =2

    "'Back Button_13' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.Filter
        OnSelect: =Navigate('Training Tracker - Home', ScreenTransition.Cover)
        Width: =40
        X: =Parent.Width - 80
        Y: =Container3_1.Height / 2 - 21
        ZIndex: =3

    "'Back Button_14' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.CalendarBlank
        OnSelect: |-
            =Set(trainingsCalendarView, true);
            Set(trainingsListView, false);
        Visible: =trainingsListView
        Width: =40
        X: =Parent.Width - 140
        Y: =Container3_1.Height / 2 - 21
        ZIndex: =4

    "'Back Button_15' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ListScrollWatchlist
        OnSelect: |-
            =Set(trainingsCalendarView, false);
            Set(trainingsListView, true);
        Visible: =trainingsCalendarView
        Width: =40
        X: =Parent.Width - 140
        Y: =Container3_1.Height / 2 - 21
        ZIndex: =5

