"'Training Tracker - MCLE Certificate Chooser Single' As screen":

    Container12_1 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutAlignItems: =LayoutAlignItems.Stretch
        LayoutDirection: =LayoutDirection.Vertical
        LayoutGap: =20
        LayoutJustifyContent: =LayoutJustifyContent.SpaceBetween
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        Container14_4 As groupContainer.verticalAutoLayoutContainer:
            AlignInContainer: =AlignInContainer.SetByContainer
            Fill: =fxTheme.Header.BGColor
            FillPortions: =0
            Height: ='Background Color_9'.Height
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            Width: ='Background Color_9'.Width
            X: =
            Y: =
            ZIndex: =1

            Icon11_4 As icon.ArrowLeft:
                Color: =fxTheme.Header.TextColor
                Icon: =Icon.ArrowLeft
                OnSelect: =Back();
                X: =40
                Y: =40
                ZIndex: =1

            Label15_5 As label:
                Align: =Align.Center
                Color: =fxTheme.Header.TextColor
                Font: =Font.Lato
                Height: =70
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =25
                Text: ="Generate Certificates"
                Width: =487
                X: =115
                Y: =15
                ZIndex: =2

        Label20_1 As label:
            Height: =70
            LayoutMinHeight: =70
            LayoutMinWidth: =560
            Size: =21
            Text: |-
                ="Attendees:"
            Width: =560
            ZIndex: =4

        ComboBox4_1 As combobox:
            DefaultSelectedItems: =
            DisplayFields: =["Name","AttendedTime"]
            FillPortions: =1
            Height: =70
            Items: |-
                =ForAll(Filter(MCLETrainingAttendance, TrainingID = Training.ID, 'Check-InTime' <> Blank(), 'Checkout Time' <> Blank()), {
                    Name: ThisRecord.Attendee,
                    ID: ThisRecord.ID,
                    AttendedTime: Concatenate(Text(DateDiff(ThisRecord.'Check-InTime', ThisRecord.'Checkout Time', TimeUnit.Minutes)), " min"),
                    CO: ThisRecord.'Checkout Time',
                    CI: ThisRecord.'Check-InTime'
                })
            LayoutMinHeight: =70
            LayoutMinWidth: =575
            OnSelect: |-
                =UpdateContext({test: Self.SelectedItems})
            SearchFields: =["AttendedTime"]
            SearchItems: |-
                =Search(ForAll(Filter(MCLETrainingAttendance, TrainingID = Training.ID, 'Check-InTime' <> Blank(), 'Checkout Time' <> Blank()), {
                    Name: ThisRecord.Attendee,
                    ID: ThisRecord.ID,
                    AttendedTime: Concatenate(Text(DateDiff(ThisRecord.'Check-InTime', ThisRecord.'Checkout Time', TimeUnit.Minutes)), " min"),
                    CO: ThisRecord.'Checkout Time',
                    CI: ThisRecord.'Check-InTime'
                }),ComboBox4_1.SearchText,"AttendedTime")
            Size: =21
            Template: =ListItemTemplate.Double
            Width: =575
            ZIndex: =5

        Button1_1 As button:
            Height: =70
            LayoutMinHeight: =70
            LayoutMinWidth: =280
            OnSelect: |-
                =Navigate('Training Tracker - MCLE Certificate', ScreenTransition.Cover, {AttendanceRecords: ComboBox4_1.SelectedItems})
            Size: =24
            Text: ="Generate Certificates"
            Width: =280
            ZIndex: =6

