"'Training-CalRSVP' As screen":

    "'Background Color_10' As rectangle":
        BorderStyle: =BorderStyle.None
        Fill: =RGBA(25, 53, 110, 1)
        Height: =111
        Width: =640
        ZIndex: =1

    Label4_5 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Height: =70
        Size: =26
        Text: ="RSVP"
        Width: =560
        X: =40
        Y: =20
        ZIndex: =2

    Button1_3 As button:
        Fill: =RGBA(25, 53, 110, 1)
        Height: =58
        OnSelect: =Navigate('Training - Calendar', ScreenTransition.CoverRight); Set(IsSidebarOpen, !IsSidebarOpen)
        Size: =24
        Text: ="Cancel"
        Width: =178
        X: =109
        Y: =530
        ZIndex: =3

    Button2_1 As button:
        Fill: =RGBA(25, 53, 110, 1)
        Height: =58
        OnSelect: =
        Size: =24
        Text: ="Submit"
        Width: =178
        X: =352
        Y: =530
        ZIndex: =4

    Label5_2 As label:
        Color: =RGBA(255, 0, 0, 1)
        Height: =80
        Size: =21
        Text: = _selectedCalendarEvent.Subject
        Width: =600
        X: =40
        Y: =259
        ZIndex: =5

    "'Back Button_11' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ArrowLeft
        OnSelect: =Back( ScreenTransition.Cover)
        Width: =40
        X: =26
        Y: =33
        ZIndex: =6

