"'Training Tracker - Check In' As screen":

    Container1_4 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        ZIndex: =1

        Container3_9 As groupContainer.horizontalAutoLayoutContainer:
            Fill: =RGBA(0, 16, 96, 1)
            Height: =225
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =1

            HomeTitle_4 As label:
                Align: =Align.Center
                AlignInContainer: =AlignInContainer.Center
                Color: =RGBA(255, 255, 255, 1)
                Font: =Font.Lato
                Height: =74
                LayoutMinHeight: =70
                LayoutMinWidth: =560
                Size: =26
                Text: ="Check-In"
                Width: =Parent.Width
                X: =83
                Y: =127
                ZIndex: =1

        Container4_3 As groupContainer.verticalAutoLayoutContainer:
            FillPortions: =7
            Height: =225
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            ZIndex: =2

            Container9_1 As groupContainer.manualLayoutContainer:
                Height: =Parent.Height
                LayoutMinHeight: =112
                LayoutMinWidth: =250
                Width: =Parent.Width
                ZIndex: =1

                Button7_1 As button:
                    Height: =70
                    OnSelect: =Navigate('Training Tracker - Check In', ScreenTransition.CoverRight);
                    Size: =24
                    Text: ="Check-In"
                    Width: =Parent.Width - 120
                    X: =54
                    Y: =882
                    ZIndex: =17

    "'Back Button_17' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ArrowLeft
        OnSelect: =Navigate('Training Tracker - View Training Details', ScreenTransition.Cover)
        Width: =40
        X: =30
        Y: =Container3_9.Height / 2 - 21
        ZIndex: =2

