Trainings As screen:

    Container2 As groupContainer.manualLayoutContainer:
        Height: =940
        Width: =Parent.Width
        Y: =196
        ZIndex: =1

        "Gallery1 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0'":
            DelayItemLoading: =true
            Height: =762
            Items: =MCLETrainings_1
            Layout: =Layout.Vertical
            LoadingSpinner: =LoadingSpinner.Data
            TemplatePadding: =0
            TemplateSize: =104
            Y: =40
            ZIndex: =1

            Image1 As image:
                Height: =72
                Image: =ThisItem.VideoIcon
                OnSelect: =Select(Parent)
                RadiusBottomLeft: =8
                RadiusBottomRight: =8
                RadiusTopLeft: =8
                RadiusTopRight: =8
                Width: =72
                X: =16
                Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                ZIndex: =1

            eDate As label:
                FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                Height: =38
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =18
                Text: =ThisItem.TrainingEndDay
                VerticalAlign: =VerticalAlign.Top
                Width: =424
                X: =88
                Y: =66
                ZIndex: =2

            sDate As label:
                FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                Height: =Self.Size * 1.8
                OnSelect: =Select(Parent)
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Size: =18
                Text: =ThisItem.TrainingStartDate & " - "
                VerticalAlign: =VerticalAlign.Top
                Width: =eDate.Width
                X: =88
                Y: =37
                ZIndex: =3

            Separator5 As rectangle:
                Height: =8
                OnSelect: =Select(Parent)
                Width: =Parent.TemplateWidth
                Y: =Parent.TemplateHeight - Self.Height
                ZIndex: =5

            Rectangle2_1 As rectangle:
                Height: =Parent.TemplateHeight - Separator5.Height
                OnSelect: =Select(Parent)
                Visible: =ThisItem.IsSelected
                Width: =4
                ZIndex: =6

            Button4 As button:
                Fill: =RGBA(25, 53, 110, 1)
                Height: =54
                OnSelect: =SendEmailAddEvent.Run(ThisItem.TrainingStartDate, ThisItem.TrainingEndDay, User().Email, ThisItem.Training,ThisItem.TrainingType);
                Size: =24
                Text: ="Button"
                Width: =123
                X: =467
                Y: =20
                ZIndex: =7

            Subject As label:
                Height: =37
                OnSelect: =Select(Parent)
                Size: =21
                Text: =ThisItem.Training
                Width: =406
                X: =117
                ZIndex: =8

    RectQuickActionBar2_1 As rectangle:
        Fill: =RGBA(25, 53, 110, 1)
        Height: =88
        Width: =Parent.Width
        ZIndex: =2

    "'Back Button_9' As icon.ArrowLeft":
        Color: =RGBA(255, 255, 255, 1)
        Height: =43
        Icon: =Icon.ArrowLeft
        OnSelect: =Back( ScreenTransition.Cover)
        Width: =40
        X: =34
        Y: =22
        ZIndex: =3

    IconRefresh1_2 As icon.Reload:
        AccessibleLabel: =Self.Tooltip
        Height: =88
        Icon: =Icon.Reload
        OnSelect: =Refresh(SiteVideoandTimes)
        PaddingBottom: =22
        PaddingLeft: =22
        PaddingRight: =22
        PaddingTop: =22
        TabIndex: =0
        Tooltip: ="Refresh list"
        Width: =88
        X: =548
        Y: =4
        ZIndex: =4

    IconSortUpDown1_2 As icon.ArrowsUpDown:
        AccessibleLabel: =Self.Tooltip
        Height: =88
        Icon: =Icon.Sort
        OnSelect: |-
            =UpdateContext({SortDescending1: !SortDescending1})
        PaddingBottom: =26
        PaddingLeft: =26
        PaddingRight: =26
        PaddingTop: =26
        TabIndex: =0
        Tooltip: =If(SortDescending1, "Sort list in reverse alphabetical order", "Sort list in alphabetical order")
        Width: =88
        X: =500
        Y: =4
        ZIndex: =5

    TextSearchBox1_3 As text:
        Default: =""
        Height: =68
        HintText: ="Search items"
        PaddingLeft: =70
        RadiusBottomLeft: =0
        RadiusBottomRight: =7
        RadiusTopLeft: =0
        RadiusTopRight: =7
        Size: =21
        Width: =Parent.Width
        Y: =88
        ZIndex: =6

    Icon13 As icon.Search:
        Icon: =Icon.Search
        X: =10
        Y: =92
        ZIndex: =7

    Button2_3 As button:
        BorderColor: =ColorFade(Button2_3.Fill, -15%)
        Color: =RGBA(255,255,255,1)
        DisabledBorderColor: =ColorFade(Button2_3.BorderColor, 70%)
        DisabledColor: =ColorFade(RGBA(47, 41, 43, 1), 70%)
        DisabledFill: =ColorFade(RGBA(159, 167, 165, 1), 50%)
        DisplayMode: =DisplayMode.View
        Fill: =RGBA(245, 247, 249, 1)
        FocusedBorderColor: =Button2_3.BorderColor
        FocusedBorderThickness: =0
        Height: =90
        HoverBorderColor: =ColorFade(Button2_3.BorderColor, 20%)
        HoverColor: =Button2_3.Color
        HoverFill: =ColorFade(Button2_3.Fill, 20%)
        PressedBorderColor: =Button2_3.Fill
        PressedColor: =Button2_3.Fill
        PressedFill: =Button2_3.Color
        RadiusBottomLeft: =4
        RadiusBottomRight: =4
        RadiusTopLeft: =4
        RadiusTopRight: =4
        Text: =""
        Width: =640
        Y: =1046
        ZIndex: =8

    Circle2_7 As circle:
        Fill: =RGBA(25, 53, 110, 1)
        Height: =80
        OnSelect: |
            =false
        Width: =80
        X: =556
        Y: =92
        ZIndex: =9

    Label3_9 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Height: =26
        OnSelect: |
            =false
        Size: =14
        Text: ="Team"
        Width: =80
        X: =556
        Y: =172
        ZIndex: =10

    Icon6_1 As icon.CalendarBlank:
        Color: =RGBA(255, 255, 255, 1)
        Height: =37
        Icon: =Icon.CalendarBlank
        OnSelect: =Navigate('Training - Calendar', ScreenTransition.CoverRight)
        Width: =51
        X: =570
        Y: =113
        ZIndex: =11

